/* 시퀀스 생성 */
CREATE SEQUENCE SEQ_SALES_NUMBER
	INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPORT_NUMBER
	INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBER_NUMBER
	INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTICE_NUMBER
	INCREMENT BY 1;
CREATE SEQUENCE SEQ_SCRAP_NUMBER
	INCREMENT BY 1;

/* 신고게시판 */
CREATE TABLE REPORT (
	REPORT_NUMBER NUMBER(10) NOT NULL, /* 글번호 */
	MEMBER_ID VARCHAR2(255), /* 회원아이디 */
	REPORT_DATE DATE, /* 신고일자 */
	REPORT_TITLE VARCHAR2(255), /* 제목 */
	REPORT_CONTENT VARCHAR2(255), /* 내용 */
	CHECK_COMPLETE NUMBER(2), /* 처리여부 */
	SALES_NUMBER NUMBER(20) /* 매물번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

CREATE UNIQUE INDEX PK_REPORT
	ON REPORT (
		REPORT_NUMBER ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE REPORT
	ADD
		CONSTRAINT PK_REPORT
		PRIMARY KEY (
			REPORT_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 매물목록 */
CREATE TABLE SALES (
	SALES_NUMBER NUMBER(20) NOT NULL, /* 매물번호 */
	SALES_TITLE VARCHAR2(255), /* 매물제목 */
	MEMBER_ID VARCHAR2(50), /* 아이디 */
	SALES_DATE DATE, /* 등록날짜 */
	SALES_CONTENT VARCHAR2(255), /* 매물내용 */
	SALES_CATEGORY_TYPE VARCHAR2(255), /* 매물유형 */
	SALES_CATEGORY_RENT VARCHAR2(255), /* 매매전월세 */
	SALES_DEPOSIT NUMBER(30), /* 보증금 */
	SALES_COST NUMBER(30), /* 매매가 */
	SALES_FACTOR_TOTAL NUMBER(10), /* 지수 */
	SALES_AREA NUMBER(10,5), /* 면적 */
	SALES_ADDRESS VARCHAR2(255), /* 주소 */
	SALES_CHECK_BLIND NUMBER(10), /* 신고처리유무 */
	SALES_COUNT NUMBER(10), /* 조회수 */
	SALES_OPTION VARCHAR2(125), /* 옵션 */
	SALES_BUILD_YEAR VARCHAR2(25), /* 준공년도 */
	SALES_FLOOR VARCHAR2(20) /* 층수 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

CREATE UNIQUE INDEX PK_SALES
	ON SALES (
		SALES_NUMBER ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE SALES
	ADD
		CONSTRAINT PK_SALES
		PRIMARY KEY (
			SALES_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 매물이미지 */
CREATE TABLE SALES_IMG (
	IMAGE_INDEX NUMBER(10) NOT NULL, /* 이미지순서 */
	IMAGE_URL VARCHAR2(255), /* 이미지경로 */
	SALES_NUMBER NUMBER(20) /* 매물번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_NUMBER NUMBER(10) NOT NULL, /* 공지사항번호 */
	NOTICE_TITLE VARCHAR2(255), /* 제목 */
	NOTICE_DATE DATE, /* 등록날짜 */
	NOTICE_CONTENT VARCHAR2(2048), /* 내용 */
	NOTICE_COUNT NUMBER(10), /* 조회수 */
	MEMBER_ID VARCHAR2(50) /* 아이디 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTICE_NUMBER ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 스크랩 */
CREATE TABLE SCRAP (
	MEMBER_ID VARCHAR2(255) NOT NULL, /* 회원아이디 */
	SCRAP_NUMBER NUMBER(20) NOT NULL, /* 스크랩번호 */
	SALES_NUMBER NUMBER(20) /* 매물번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

/* 회원 */
CREATE TABLE MEMBER (
	MEMBER_ID VARCHAR2(50) NOT NULL, /* 아이디 */
	MEMBER_NUMBER NUMBER(20) NOT NULL, /* 회원번호 */
	MEMBER_NAME VARCHAR2(255) NOT NULL, /* 회원이름 */
	MEMBER_EMAIL VARCHAR2(255), /* 이메일 */
	MEMBER_PHONE VARCHAR2(255), /* 전화번호 */
	MEMBER_LEVEL VARCHAR2(255), /* 회원등급 */
	MEMBER_REGISTER_DATE DATE /* 등록날짜 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		MEMBER_ID ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			MEMBER_ID
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 지수 */
CREATE TABLE FACTOR (
	SALES_NUMBER NUMBER(20) NOT NULL, /* 매물번호 */
	FACTOR_TOTAL NUMBER(20), /* 총지수 */
	FACTOR_GAS NUMBER(20), /* 주유소 */
	FACTOR_HOSPITAL NUMBER(20), /* 병원 */
	FACTOR_TOUR NUMBER(20), /* 관광명소 */
	FACTOR_PUBLIC NUMBER(20), /* 공공기관 */
	FACTOR_MART NUMBER(20) /* 대형마트 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

CREATE UNIQUE INDEX PK_FACTOR
	ON FACTOR (
		SALES_NUMBER ASC
	)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	NOLOGGING
	NOCOMPRESS
	SORT
	NOPARALLEL;

ALTER TABLE FACTOR
	ADD
		CONSTRAINT PK_FACTOR
		PRIMARY KEY (
			SALES_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 공지사항이미지 */
CREATE TABLE NOTICE_IMG (
	IMAGE_INDEX NUMBER(10), /* 이미지순서 */
	IMAGE_URL VARCHAR2(255), /* 이미지경로 */
	NOTICE_NUMBER NUMBER(10) /* 공지사항번호 */
)
	STORAGE (
		BUFFER_POOL DEFAULT
	)
	LOGGING
	NOCOMPRESS
	NOCACHE
	NOPARALLEL
	NOROWDEPENDENCIES
	DISABLE ROW MOVEMENT;

ALTER TABLE REPORT
	ADD
		CONSTRAINT FK_SALES_TO_REPORT
		FOREIGN KEY (
			SALES_NUMBER
		)
		REFERENCES SALES (
			SALES_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE SALES
	ADD
		CONSTRAINT FK_MEMBER_TO_SALES
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE SALES_IMG
	ADD
		CONSTRAINT FK_SALES_TO_SALES_IMG
		FOREIGN KEY (
			SALES_NUMBER
		)
		REFERENCES SALES (
			SALES_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_MEMBER_TO_NOTICE
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE SCRAP
	ADD
		CONSTRAINT FK_SALES_TO_SCRAP
		FOREIGN KEY (
			SALES_NUMBER
		)
		REFERENCES SALES (
			SALES_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE FACTOR
	ADD
		CONSTRAINT FK_SALES_TO_FACTOR
		FOREIGN KEY (
			SALES_NUMBER
		)
		REFERENCES SALES (
			SALES_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE NOTICE_IMG
	ADD
		CONSTRAINT FK_NOTICE_TO_NOTICE_IMG
		FOREIGN KEY (
			NOTICE_NUMBER
		)
		REFERENCES NOTICE (
			NOTICE_NUMBER
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;